### ISSUE TITLE
Enhance hadoop's RandomTextWriter to allow for manipulation of key sizes

### ISSUE THREAD

**Issue by js9045** [Xockets/HiBench#1]
We have the need to manipulate key sizes to perform some functional testing.

The default version of RandomTextWriter creates sentences for both keys and values from a static dictionary by appending a whitespace between words.  There are already configuration parameters to specify the words to use for keys and values independently.

The enhancements we need are:
- Add a method to build long words.  Instead of inserting a whitespace, simply append multiple words together.
- use the long words method to build the keys, controlled by the existing min and max parameters

**Comment by js9045** [comment]
@aldrinleal I took at stab at this in this [here](https://github.com/Xockets/HiBench/blob/js9045/test_2_1/src/autogen/src/main/java/org/apache/hadoop/examples/XocketsRandomTextWriter.java)

Functionally it does what it needs, but its failing when I run the HiBench prepare script using my version.  Here is the failure, followed by some background on how I got here.

```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interfa
ce org.apache.hadoop.mapreduce.JobContext, but class was expected
    at org.apache.hadoop.examples.XocketsRandomWriter$RandomInputFormat.getS
plits(XocketsRandomWriter.java:113)
    at org.apache.hadoop.mapreduce.JobSubmitter.writeNewSplits(JobSubmitter.
java:597)
    at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.jav
a:614)
    at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitt
er.java:492)
    at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1306)
    at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1303)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInforma
tion.java:1671)
    at org.apache.hadoop.mapreduce.Job.submit(Job.java:1303)
    at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1324)
    at org.apache.hadoop.examples.XocketsRandomTextWriter.run(XocketsRandomT
extWriter.java:251)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at org.apache.hadoop.examples.XocketsRandomTextWriter.main(XocketsRandom
TextWriter.java:262)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
[dan@tarantino ~]$ 
```

This might not be the right approach of introducing these changes.
Note that the HiBench repository already had the `src/autogen/src/main/java/org/apache/hadoop` path.
- First I tried to create my own version of RandomTextWriter within the HiBench org/apache/hadoop and by pointing the prepare script to the HiBench jar, but it wasn't picking it up.
- Then I tried to create my own generation class under `src/autogen/src/main/java/HiBench/` but I couldn't import the Random*Writer classes from the hadoop examples package.
- The last thing I tried was renaming my classes so they wouldn't clash with the org/apache ones, but then I seem to be falling into some dependency trap.

**Comment by aldrinleal** [comment]
It is related to this one:

https://github.com/intel-hadoop/HiBench/issues/112

Need to remember how I solved it

**Comment by aldrinleal** [comment]
How are you running it? Seems all you need is to build with MR2 as outlined here:

https://github.com/intel-hadoop/HiBench/wiki/Getting-Started

```
$ cd autogen
$ mvn -PMR2 package
```

**Comment by aldrinleal** [comment]
That was just the beginning. I'll need to port it to the new MRv2 API completely, but thats doable

**Comment by js9045** [comment]
It might be easier to just copy over the MR2 version and make the
modifications?   I missed the mvn option for the build :(

**Comment by js9045** [comment]
@aldrinleal do you have something to push in?  BTW, I'm going to create a new branch 'xockets-master' in this fork to use as our master.

**Comment by js9045** [comment]
@aldrinleal I got my branch to build with your suggestion.  Haven't been able to test it yet as I've been updating the cluster to 5.5 all day :(

**Comment by aldrinleal** [comment]
I've pushed a few tweaks to run on 5.5. Simply `mvn clean package` prior to running should work

**Comment by js9045** [comment]
@aldrinleal Did you try running the prepare.sh script on the wordcount workload?  I'm still seeing the failue (after a mvn clean package): 

```
[dan@tarantino wordcount]$ cd prepare/
[dan@tarantino prepare]$ ./prepare.sh 
patching args=
Parsing conf: /home/dan/GIT/js9045-HiBench/conf/00-default-properties.conf
Parsing conf: /home/dan/GIT/js9045-HiBench/conf/01-default-streamingbench.conf
Parsing conf: /home/dan/GIT/js9045-HiBench/conf/10-data-scale-profile.conf
Parsing conf: /home/dan/GIT/js9045-HiBench/conf/20-samza-common.conf
Parsing conf: /home/dan/GIT/js9045-HiBench/conf/30-samza-workloads.conf
Parsing conf: /home/dan/GIT/js9045-HiBench/conf/99-user_defined_properties.conf
Parsing conf: /home/dan/GIT/js9045-HiBench/workloads/wordcount/conf/00-wordcount-default.conf
Parsing conf: /home/dan/GIT/js9045-HiBench/workloads/wordcount/conf/10-wordcount-userdefine.conf
Probing spark verison, may last long at first time...
probe sleep jar: /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-mapreduce-client-jobclient-tests.jar
start HadoopPrepareWordcount bench
hdfs rm -r: /etc/alternatives/hadoop --config /opt/cloudera/parcels/CDH/lib/hadoop/etc/hadoop fs -rm -r -skipTrash hdfs://192.168.3.112:8020/user/dan/HiBench/Wordcount/Input.x_2_1
rm: Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error

Submit MapReduce Job: /etc/alternatives/hadoop --config /opt/cloudera/parcels/CDH/lib/hadoop/etc/hadoop jar /home/dan/GIT/js9045-HiBench/src/autogen/target/autogen-5.0-SNAPSHOT-jar-with-dependencies.jar org.apache.hadoop.examples.XocketsRandomTextWriter -D mapreduce.randomtextwriter.minwordskey=100 -D mapreduce.randomtextwriter.maxwordskey=100 -D mapreduce.randomtextwriter.totalbytes=32000 -D mapreduce.job.maps=1 -D mapreduce.job.reduces=1 -D mapreduce.output.fileoutputformat.compress=false hdfs://192.168.3.112:8020/user/dan/HiBench/Wordcount/Input.x_2_1
15/12/14 09:18:36 WARN security.UserGroupInformation: PriviledgedActionException as:dan (auth:SIMPLE) cause:org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
Exception in thread "main" org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
ERROR: Hadoop job /home/dan/GIT/js9045-HiBench/src/autogen/target/autogen-5.0-SNAPSHOT-jar-with-dependencies.jar org.apache.hadoop.examples.XocketsRandomTextWriter failed to run successfully.
Hint: You can goto /home/dan/GIT/js9045-HiBench/report/wordcount/prepare/conf/../bench.log to check for detailed log.
Opening log tail for you:

    at org.apache.hadoop.mapreduce.Job.submit(Job.java:1304)
    at org.apache.hadoop.examples.XocketsRandomTextWriter.run(XocketsRandomTextWriter.java:263)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at org.apache.hadoop.examples.XocketsRandomTextWriter.main(XocketsRandomTextWriter.java:279)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
[dan@tarantino prepare]$ 
```

**Comment by js9045** [comment]
@aldrinleal I've disabled HDFS HA on the cluster and things look better. The job ran successfully.

**Comment by js9045** [comment]
@aldrinleal Thanks for your help.

**Comment by Dillip321** [comment]
I am facing same issues, Not sure how to procede, I have checked my hdfs-site.xml, failover looks mentioned. if i will disabled HDFS HA, Do i need to restart it or what >
